package com.bit.bitb.biz.entity;

// Generated 2013-5-11 23:15:46 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BtcHistory generated by hbm2java
 */
@Entity
@Table(name = "btc_history", catalog = "test")
public class BtcHistory implements java.io.Serializable {

	private int idbtchistory;
	private String iduser;
	private Float quantity;
	private Character type;
	private String memo;
	private Date createTs;
	private Date modifyTs;

	public BtcHistory() {
	}

	public BtcHistory(int idbtchistory) {
		this.idbtchistory = idbtchistory;
	}

	public BtcHistory(int idbtchistory, String iduser, Float quantity,
			Character type, String memo, Date createTs, Date modifyTs) {
		this.idbtchistory = idbtchistory;
		this.iduser = iduser;
		this.quantity = quantity;
		this.type = type;
		this.memo = memo;
		this.createTs = createTs;
		this.modifyTs = modifyTs;
	}

	@Id
	@Column(name = "idbtchistory", unique = true, nullable = false)
	public int getIdbtchistory() {
		return this.idbtchistory;
	}

	public void setIdbtchistory(int idbtchistory) {
		this.idbtchistory = idbtchistory;
	}

	@Column(name = "iduser", length = 45)
	public String getIduser() {
		return this.iduser;
	}

	public void setIduser(String iduser) {
		this.iduser = iduser;
	}

	@Column(name = "quantity", precision = 12, scale = 0)
	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "memo", length = 45)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_ts", length = 19)
	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_ts", length = 19)
	public Date getModifyTs() {
		return this.modifyTs;
	}

	public void setModifyTs(Date modifyTs) {
		this.modifyTs = modifyTs;
	}

}
