package com.bit.bitb.biz.entity;

// Generated Apr 29, 2013 8:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Btcrecharge generated by hbm2java
 */
@Entity
@Table(name = "btcrecharge", catalog = "test")
public class Btcrecharge implements java.io.Serializable {

	private int idbtcrecharge;
	private String iduser;
	private Character type;
	private Float qty;
	private Date date;
	private String userIduser;

	public Btcrecharge() {
	}

	public Btcrecharge(int idbtcrecharge, String userIduser) {
		this.idbtcrecharge = idbtcrecharge;
		this.userIduser = userIduser;
	}

	public Btcrecharge(int idbtcrecharge, String iduser, Character type,
			Float qty, Date date, String userIduser) {
		this.idbtcrecharge = idbtcrecharge;
		this.iduser = iduser;
		this.type = type;
		this.qty = qty;
		this.date = date;
		this.userIduser = userIduser;
	}

	@Id
	@Column(name = "idbtcrecharge", unique = true, nullable = false)
	public int getIdbtcrecharge() {
		return this.idbtcrecharge;
	}

	public void setIdbtcrecharge(int idbtcrecharge) {
		this.idbtcrecharge = idbtcrecharge;
	}

	@Column(name = "iduser", length = 45)
	public String getIduser() {
		return this.iduser;
	}

	public void setIduser(String iduser) {
		this.iduser = iduser;
	}

	@Column(name = "type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "qty", precision = 12, scale = 0)
	public Float getQty() {
		return this.qty;
	}

	public void setQty(Float qty) {
		this.qty = qty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "user_iduser", nullable = false, length = 20)
	public String getUserIduser() {
		return this.userIduser;
	}

	public void setUserIduser(String userIduser) {
		this.userIduser = userIduser;
	}

}
