package com.bit.bitb.biz.entity;

// Generated 2013-5-11 23:15:46 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deal generated by hbm2java
 */
@Entity
@Table(name = "deal", catalog = "test")
public class Deal implements java.io.Serializable {

	private int iddeal;
	private String buyer;
	private String seller;
	private String idbuying;
	private String idselling;
	private String initiator;
	private String memo;
	private String price;
	private String quantity;
	private Date createTs;
	private Date modifyTs;

	public Deal() {
	}

	public Deal(int iddeal) {
		this.iddeal = iddeal;
	}

	public Deal(int iddeal, String buyer, String seller, String idbuying,
			String idselling, String initiator, String memo, String price,
			String quantity, Date createTs, Date modifyTs) {
		this.iddeal = iddeal;
		this.buyer = buyer;
		this.seller = seller;
		this.idbuying = idbuying;
		this.idselling = idselling;
		this.initiator = initiator;
		this.memo = memo;
		this.price = price;
		this.quantity = quantity;
		this.createTs = createTs;
		this.modifyTs = modifyTs;
	}

	@Id
	@Column(name = "iddeal", unique = true, nullable = false)
	public int getIddeal() {
		return this.iddeal;
	}

	public void setIddeal(int iddeal) {
		this.iddeal = iddeal;
	}

	@Column(name = "buyer", length = 45)
	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	@Column(name = "seller", length = 45)
	public String getSeller() {
		return this.seller;
	}

	public void setSeller(String seller) {
		this.seller = seller;
	}

	@Column(name = "idbuying", length = 45)
	public String getIdbuying() {
		return this.idbuying;
	}

	public void setIdbuying(String idbuying) {
		this.idbuying = idbuying;
	}

	@Column(name = "idselling", length = 45)
	public String getIdselling() {
		return this.idselling;
	}

	public void setIdselling(String idselling) {
		this.idselling = idselling;
	}

	@Column(name = "initiator", length = 45)
	public String getInitiator() {
		return this.initiator;
	}

	public void setInitiator(String initiator) {
		this.initiator = initiator;
	}

	@Column(name = "memo", length = 45)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "price", length = 100)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "quantity", length = 100)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_ts", length = 19)
	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_ts", length = 19)
	public Date getModifyTs() {
		return this.modifyTs;
	}

	public void setModifyTs(Date modifyTs) {
		this.modifyTs = modifyTs;
	}

}
