package com.bit.bitb.biz.entity;

// Generated Apr 29, 2013 8:09:40 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Moneyrecharge generated by hbm2java
 */
@Entity
@Table(name = "moneyrecharge", catalog = "test")
public class Moneyrecharge implements java.io.Serializable {

	private int idmoneyrecharge;
	private String iduser;
	private String type;
	private String qty;
	private String date;
	private String note;
	private String userIduser;

	public Moneyrecharge() {
	}

	public Moneyrecharge(int idmoneyrecharge, String userIduser) {
		this.idmoneyrecharge = idmoneyrecharge;
		this.userIduser = userIduser;
	}

	public Moneyrecharge(int idmoneyrecharge, String iduser, String type,
			String qty, String date, String note, String userIduser) {
		this.idmoneyrecharge = idmoneyrecharge;
		this.iduser = iduser;
		this.type = type;
		this.qty = qty;
		this.date = date;
		this.note = note;
		this.userIduser = userIduser;
	}

	@Id
	@Column(name = "idmoneyrecharge", unique = true, nullable = false)
	public int getIdmoneyrecharge() {
		return this.idmoneyrecharge;
	}

	public void setIdmoneyrecharge(int idmoneyrecharge) {
		this.idmoneyrecharge = idmoneyrecharge;
	}

	@Column(name = "iduser", length = 45)
	public String getIduser() {
		return this.iduser;
	}

	public void setIduser(String iduser) {
		this.iduser = iduser;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "qty", length = 45)
	public String getQty() {
		return this.qty;
	}

	public void setQty(String qty) {
		this.qty = qty;
	}

	@Column(name = "date", length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "user_iduser", nullable = false, length = 20)
	public String getUserIduser() {
		return this.userIduser;
	}

	public void setUserIduser(String userIduser) {
		this.userIduser = userIduser;
	}

}
