package com.bit.bitb.biz.entity;

// Generated 2013-5-11 23:15:46 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MoneyHistory generated by hbm2java
 */
@Entity
@Table(name = "money_history", catalog = "test")
public class MoneyHistory implements java.io.Serializable {

	private int idmoneyhistory;
	private String iduser;
	private String quantity;
	private String type;
	private String memo;
	private Date createTs;
	private Date modifyTs;

	public MoneyHistory() {
	}

	public MoneyHistory(int idmoneyhistory) {
		this.idmoneyhistory = idmoneyhistory;
	}

	public MoneyHistory(int idmoneyhistory, String iduser, String quantity,
			String type, String memo, Date createTs, Date modifyTs) {
		this.idmoneyhistory = idmoneyhistory;
		this.iduser = iduser;
		this.quantity = quantity;
		this.type = type;
		this.memo = memo;
		this.createTs = createTs;
		this.modifyTs = modifyTs;
	}

	@Id
	@Column(name = "idmoneyhistory", unique = true, nullable = false)
	public int getIdmoneyhistory() {
		return this.idmoneyhistory;
	}

	public void setIdmoneyhistory(int idmoneyhistory) {
		this.idmoneyhistory = idmoneyhistory;
	}

	@Column(name = "iduser", length = 45)
	public String getIduser() {
		return this.iduser;
	}

	public void setIduser(String iduser) {
		this.iduser = iduser;
	}

	@Column(name = "quantity", length = 45)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "memo", length = 45)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_ts", length = 19)
	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_ts", length = 19)
	public Date getModifyTs() {
		return this.modifyTs;
	}

	public void setModifyTs(Date modifyTs) {
		this.modifyTs = modifyTs;
	}

}
