package com.bit.bitb.biz.entity;

// Generated Apr 29, 2013 8:09:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "test")
public class User implements java.io.Serializable {

	private String iduser;
	private String username;
	private Date birthday;
	private Character gender;
	private String mobile;
	private Float btcbalance;
	private Float moneybalance;
	private String realname;
	private String email;
	private String qq;
	private String weibo;
	private String address;

	public User() {
	}

	public User(String iduser) {
		this.iduser = iduser;
	}

	public User(String iduser, String username, Date birthday,
			Character gender, String mobile, Float btcbalance,
			Float moneybalance, String realname, String email, String qq,
			String weibo, String address) {
		this.iduser = iduser;
		this.username = username;
		this.birthday = birthday;
		this.gender = gender;
		this.mobile = mobile;
		this.btcbalance = btcbalance;
		this.moneybalance = moneybalance;
		this.realname = realname;
		this.email = email;
		this.qq = qq;
		this.weibo = weibo;
		this.address = address;
	}

	@Id
	@Column(name = "iduser", unique = true, nullable = false, length = 20)
	public String getIduser() {
		return this.iduser;
	}

	public void setIduser(String iduser) {
		this.iduser = iduser;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "btcbalance", precision = 12, scale = 0)
	public Float getBtcbalance() {
		return this.btcbalance;
	}

	public void setBtcbalance(Float btcbalance) {
		this.btcbalance = btcbalance;
	}

	@Column(name = "moneybalance", precision = 12, scale = 0)
	public Float getMoneybalance() {
		return this.moneybalance;
	}

	public void setMoneybalance(Float moneybalance) {
		this.moneybalance = moneybalance;
	}

	@Column(name = "realname", length = 200)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "qq", length = 45)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "weibo", length = 45)
	public String getWeibo() {
		return this.weibo;
	}

	public void setWeibo(String weibo) {
		this.weibo = weibo;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
